"""empty message

Revision ID: 75453fcdd773
Revises: 7dd0de1b37e0
Create Date: 2017-12-06 10:19:57.782725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75453fcdd773'
down_revision = '7dd0de1b37e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plc_alarm', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plc_alarm', sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
