"""empty message

Revision ID: 7dd0de1b37e0
Revises: 2671f9b6958f
Create Date: 2017-12-04 16:31:32.486173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dd0de1b37e0'
down_revision = '2671f9b6958f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('var_id', sa.Integer(), nullable=True))
    op.drop_constraint('values_ibfk_1', 'values', type_='foreignkey')
    op.create_foreign_key(None, 'values', 'yjvariableinfo', ['var_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('values', 'variable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('variable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.create_foreign_key('values_ibfk_1', 'values', 'yjvariableinfo', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('values', 'var_id')
    # ### end Alembic commands ###
