"""waijanshanchu

Revision ID: e5de966682fc
Revises: a6bbdda86fcc
Create Date: 2017-10-24 14:42:57.454522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5de966682fc'
down_revision = 'a6bbdda86fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('values_ibfk_1', 'values', type_='foreignkey')
    op.create_foreign_key(None, 'values', 'yjvariableinfo', ['variable_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('yjgroupinfo_ibfk_1', 'yjgroupinfo', type_='foreignkey')
    op.create_foreign_key(None, 'yjgroupinfo', 'yjplcinfo', ['plc_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('yjplcinfo_ibfk_1', 'yjplcinfo', type_='foreignkey')
    op.create_foreign_key(None, 'yjplcinfo', 'yjstationinfo', ['station_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('yjvariableinfo_ibfk_1', 'yjvariableinfo', type_='foreignkey')
    op.create_foreign_key(None, 'yjvariableinfo', 'yjgroupinfo', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yjvariableinfo', type_='foreignkey')
    op.create_foreign_key('yjvariableinfo_ibfk_1', 'yjvariableinfo', 'yjgroupinfo', ['group_id'], ['id'])
    op.drop_constraint(None, 'yjplcinfo', type_='foreignkey')
    op.create_foreign_key('yjplcinfo_ibfk_1', 'yjplcinfo', 'yjstationinfo', ['station_id'], ['id'])
    op.drop_constraint(None, 'yjgroupinfo', type_='foreignkey')
    op.create_foreign_key('yjgroupinfo_ibfk_1', 'yjgroupinfo', 'yjplcinfo', ['plc_id'], ['id'])
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.create_foreign_key('values_ibfk_1', 'values', 'yjvariableinfo', ['variable_id'], ['id'])
    # ### end Alembic commands ###
