"""waijanshanchu

Revision ID: ea203727b731
Revises: e5de966682fc
Create Date: 2017-10-25 11:18:50.224956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea203727b731'
down_revision = 'e5de966682fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
