"""empty message

Revision ID: 11b7a88ab892
Revises: 
Create Date: 2017-03-25 11:41:38.423231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11b7a88ab892'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'yjplcinfo_ibfk_1', 'yjplcinfo', type_='foreignkey')
    op.create_foreign_key(None, 'yjplcinfo', 'yjstationinfo', ['station_id'], ['id'])
    op.drop_column('yjplcinfo', 'stationid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yjplcinfo', sa.Column('stationid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'yjplcinfo', type_='foreignkey')
    op.create_foreign_key(u'yjplcinfo_ibfk_1', 'yjplcinfo', 'yjstationinfo', ['stationid'], ['id'])
    # ### end Alembic commands ###
