"""empty message

Revision ID: 28068ed698e7
Revises: 96e60af48db2
Create Date: 2017-06-04 01:07:23.669084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28068ed698e7'
down_revision = '96e60af48db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['yjvariableinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
