"""empty message

Revision ID: 3ee99d324075
Revises: 11b7a88ab892
Create Date: 2017-03-25 12:22:19.205984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee99d324075'
down_revision = '11b7a88ab892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('get_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('values', 'get_time')
    # ### end Alembic commands ###
