"""empty message

Revision ID: 3f9bf6307b2c
Revises: 3ee99d324075
Create Date: 2017-03-30 17:13:22.257520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f9bf6307b2c'
down_revision = '3ee99d324075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('variable_name', sa.String(length=20), nullable=True))
    op.drop_constraint(u'values_ibfk_1', 'values', type_='foreignkey')
    op.drop_column('values', 'variable_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('variable_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'values_ibfk_1', 'values', 'yjvariableinfo', ['variable_id'], ['id'])
    op.drop_column('values', 'variable_name')
    # ### end Alembic commands ###
