"""empty message

Revision ID: 79d5c7423f7c
Revises: cd37bb590267
Create Date: 2017-04-11 11:41:27.389180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79d5c7423f7c'
down_revision = 'cd37bb590267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('values', 'get_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('get_time', mysql.DATETIME(), nullable=True))
    op.drop_column('values', 'date')
    # ### end Alembic commands ###
