"""empty message

Revision ID: 96e60af48db2
Revises: 
Create Date: 2017-06-04 01:04:28.238172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96e60af48db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('variable_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'values', 'yjvariableinfo', ['variable_id'], ['id'])
    op.drop_column('values', 'variable_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('values', sa.Column('variable_name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'values', type_='foreignkey')
    op.drop_column('values', 'variable_id')
    # ### end Alembic commands ###
