"""empty message

Revision ID: a5eec3670e09
Revises: 
Create Date: 2017-03-20 16:23:53.764195

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5eec3670e09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users2')
    op.drop_table('test')
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'yjgroupinfo', 'yjplcinfo', ['plcid'], ['id'])
    op.create_foreign_key(None, 'yjplcinfo', 'yjstationinfo', ['stationid'], ['id'])
    op.create_foreign_key(None, 'yjvariableinfo', 'yjgroupinfo', ['groupid'], ['id'])
    op.create_foreign_key(None, 'yjvariableinfo', 'yjplcinfo', ['plcid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yjvariableinfo', type_='foreignkey')
    op.drop_constraint(None, 'yjvariableinfo', type_='foreignkey')
    op.drop_constraint(None, 'yjplcinfo', type_='foreignkey')
    op.drop_constraint(None, 'yjgroupinfo', type_='foreignkey')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'level')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('a', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('b', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('users2',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
