"""empty message

Revision ID: c52b5fddb90a
Revises: 
Create Date: 2017-03-25 10:17:06.805716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b5fddb90a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['yjvariableinfo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('values')
    # ### end Alembic commands ###
