"""empty message

Revision ID: cd37bb590267
Revises: 3f9bf6307b2c
Create Date: 2017-03-30 18:08:53.087691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd37bb590267'
down_revision = '3f9bf6307b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yjstationinfo', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yjstationinfo', 'version')
    # ### end Alembic commands ###
